### ISSUE TITLE
write use cases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1]
## Usability Improvements (@tschawax)

- [x] multi-select UC erstellen
- [x] copy&paste UC split
- [x] restore-viewing-state UC

## Timeline (@danielsteinkogler)

- #942 

# BELOW ALL ARE DONE

Last ones:

- [x] #162
- [x] #74
- [x] #222
- [x] #288
- [x] #225
- [x] #224
- [x] #223

## @NurramoX 
- [x] printing: generate pdf with screenshot of current map with header/footer containing: current time, time of map, GPS coordinates, scale
- [x] watering layer: allows to indicate which plants/places received water at which time (+ water everywhere for rainfall). should be available offline
- [x] import/export of maps (GIS)
- [x] inform users on login when plant DB got updates and plant shouldn't be positioned anymore where it is

## @Bushuo 
- [x] timeline single selection: select a specific date: if you drag&drop elements in or out, the date is used for seeding/constructing or removing (the plant/construction).
- [x] timeline multiple selection: select range of dates: map shows all elements of that range (gray if they are not there for the whole time range), and all these elements can be edited or moved (but not added or removed)
- [x] show events in the timeline (adding+removing elements)

## @absurd-turtle

- [x] doc/usecases/calender.md should use Nextcloud calender, dates should be moveable doc/usecases/calender.md
- [x] apply for membership (accounts will be done manually in Nextcloud), invite others to join
- [x] find maps of others in Nextcloud maps (with foto, link to PermaplanT map), including an automatically-generated static map for non-members (to be shown at front page so that people know how much PermaplanT is used) [Samuel]
- [x] visit maps of other users should automatically add a text message in a "visitor chat room". It is also possible to write there something
- [x] Layer for photos and "likes/foot steps/greetings/smiles/...", with a Chat function (Nextcloud has a chat per foto) and GPS tagging (within the map); Chat layer is not needed
- [x] all nearby members get a notification when a member joins the Verein (location from profile) and are encouraged to write something
- [x] encourage nearby others on some events (e.g. when opening a map) to (virtually) visit your map (location from map properties) when you somewhat finished planning it
- [x] nextcloud login (existing login use case)
- [x] webcam
- [x] #141 buddies&friends (circles in Nextcloud)
- [x] #140 todo layer: create deck cards in your map
       offline availability (however, maybe notes can also be taken via label layer OR via drawing layer..?)

## Thorben

- [x] free membership use case
- [x] harvest basket/Erntekörbchen (to facilitate more diverse gardens and community work):
   - get good reviews in added plants
   - write good reviews
   - get good reviews when helping other people in their map
   - get good reviews of your own map
   - get new people apply for membership
- [x] serious game: good plant diversity, plan a garden with given constraints (give permissions to people to draw in alternative layers)

## Benjamin

- [x] grouping of plants
- [x] suggesting plants in-between other plants (selection based on position, without a selected plant)
- [x] incomplete groups: visually indicate when a group is not yet complete or maximal (e.g. 2 of 3 visually different than 3 of 3)
- [x] adding companions to database on different levels
- [x] reviewing companions in database (increasing confidence of companion indicators)
- [x] map-specific favorite groups
- [x] searching plants, ranking according:
   - companions of selected plant
   - plants that fit with the environment
   - plants that have higher ecological value (wild life etc.)

## already done:

- [x] revisit existing layer use case
- [x] rename layers (e.g. if several drawing layers)
- [x] #67
- [x] terrain layer
- [x] reviewing of plants
- [x] drawing layers (drawing of any shapes in any color without meaning for PermaplanT)
       offline availability
- [x] fertilize layer
       offline availability
- [x] matchmaking: find people who want to do gardening and don't have enough space for gardening (and vice-versa)
- [x] statistics: how many people entered gardens, how many plants do I have in the garden?
- [x] measuring distances
- [x] polygon for base map
- [x] ~~seeding time~~
- [x] automatic layer display/hiding, e.g. in Moisture, Infrastructure should be shown
- [x] searching of maps via keywords (including public maps of other users)
- [x] creation/deletion of map (deletion with undo for a month)
- [x] timeline: scroll bar (granularity month) and date field to change the time that is currently visible on the map
- [x] label layer
- [x] list of which plants were planted where you do not yet have seeds for (calculated from map)
- [x] entry+list of which seeds the user has (for better selection of plants), including amount and expire dates (higher recommendation of using the seed if it expires soon)
- [x] (optional) "Saisonübersicht" show plant+harvest times
- [x] (optional) mark and show favorite plants
- [x] (optional) maps can be private (public is default)
- [x] Undo should only apply to real changes, not to changes in visibility.
- [x] When drawing fields, areas or similar the width/length of field etc. should be shown next to cursor
- [x] Persistence of undo (to be discussed in #26)
- [x] deletion of plants

**Comment by markus2330** [comment]
"seeding time" usecase we can remove, it is too much.

So is now only one use case missing?

**Comment by buenaflor** [comment]
>  automatic layer display/hiding, e.g. in Moisture, Infrastructure should be shown

If I understand this correctly, if I hide everything else but display the Moisture layer, the Infrastructure will automatically be displayed as well?

**Comment by markus2330** [comment]
Exactly, but this is only an example. It is probably enough to write in the "layer visibility" use case that switching to another layer might influence which layers are active.

But we forgot about other use cases (I added them above). Please in a new PR.

**Comment by buenaflor** [comment]
Could you elaborate on:

>list of which plants were planted where you do not yet have seeds for (calculated from map)

I'm not sure I completely understand this one

**Comment by markus2330** [comment]
>  list of which plants were planted where you do not yet have seeds for (calculated from map)

Probably it is better if we also speak about it. The basic idea is: The users plan the garden with either seeds they have (their own seed catalogue) or other plants from our plant catalogue. (I.e. for some plants they have own seeds already but for others seeds are missing.) This use case is about to determine which and how many seeds the person needs to buy to be able to realize the garden as planned.

**Comment by markus2330** [comment]
@aidnurs I updated the top post with all new use cases we fancy. Probably best if we have a chat about it :wink:

**Comment by aidnurs** [comment]
Hey team,

I have a suggestion for use cases or better to say a question to be researched once we get the first version of our canvas tool:
- How map elements should be selected. Along all the layers there will be overlapping elements. Imagine a situation where the user puts multiple elements upon each other in the same layer. So the question is how should he proceed in order to modify the deepest element?


Figma provides a good example to inspire from, take a look at the screenshot below:

![Screenshot 2023-03-09 at 13 51 23](https://user-images.githubusercontent.com/28778542/224028489-a8956e3c-f6d4-479a-b971-b98427fe8e37.png)

They have a hierarchy of elements, so the user can choose an element directly from the sidebar to work with. 

This question probably belongs to the later timeline of our project, just wanted to keep the idea somewhere. Let me know what you think.

Sincerely,
Nursultan

@markus2330

**Comment by markus2330** [comment]
Thank you for the input!

In general it is better if you open new issue, unless it is about clarification of existing issues.

CAD software usually also has such hierarchy and allows visibility etc. on every subtree of the hierarchy. While it provides much more flexibility, it is also much less user friendly.

Our solution is that selection only selects objects on the enabled layer in the current time. If several layers would be selected (which is rather untypical), then you would multi-select all the elements. And exactly this is more-or-less the only reason of selecting several layers: to move whole blocks with all its objects (with all its layers). Most of the daily work happens completely within a layer.

**Comment by markus2330** [comment]
I moved a few usescases up to "unassigned". They are for people who didn't write any up to now.

**Comment by Benjaminimal** [comment]
@markus2330 
I have a few questions regarding the use cases that are assigned to me.

1. > suggesting plants in-between other plants (selection based on position, without a selected plant)

    How is this different from https://github.com/ElektraInitiative/PermaplanT/pull/120?

2. > adding companions to database on different levels

    Would anyone be able to do this or would this be restricted to some kind of admin role?
    If it can be can be done by anyone should those rules be effective for all users or only be considered for the user that added it?
    I don't think that we have defined any kind of user roles yet

3. > reviewing companions in database (increasing confidence of companion indicators)

    Do I understand this correctly? A user creates a new companionship rule which is publicly viewable.
    Any other user can comment but can't make changes.
    Would there be any kind of approval process needed?

**Comment by markus2330** [comment]
> How is this different from https://github.com/ElektraInitiative/PermaplanT/pull/120?

See requested change in #120, then there is no difference anymore.

> Would anyone be able to do this or would this be restricted to some kind of admin role?

Anyone can suggest it but it only gets available when other people with enough points reviewed it, this is part of the gamification use cases, on which @ThorbenStaufer works on. So for your part, you describe how the count of different proposals or possibly conflicting db entries/reviews lead to an overall confidence. Maybe the meeting with Pavlo with also shine new light on this.

> If it can be can be done by anyone should those rules be effective for all users or only be considered for the user that added it?

Both is possible, see above: users can globally add it or specific for a map. In map-specific rules users might say something like that they want plants with their favorite colors next to each other. This use case is not really necessarily a biological companion. Ideally there should be even a different visual representation for these map-specific rules.

>  Do I understand this correctly? A user creates a new companionship rule which is publicly viewable.

Yes. Additionally there are also map-specific rules, which might be also public (depending on the map) but are not relevant for other maps.

> Would there be any kind of approval process needed?

Yes, but also non-approved relationships can contribute to a very low confidence.

**Comment by Bushuo** [comment]
I just assigned the remaining use cases to ramzan and me.

**Comment by markus2330** [comment]
@NurramoX @Bushuo I am missing PRs from you. Use cases should be finished in the first milestone, they should have been submitted already last week.

@NurramoX I added one more use case to you: "inform users on login when plant DB got updates and plant shouldn't be positioned anymore where it is"

I reordered the sections above according to for which person is missing most.

**Comment by markus2330** [comment]
Great progress! Only 3 use cases missing! (@absurd-turtle @ThorbenStaufer)

**Comment by markus2330** [comment]
Please let us get the last use cases done! We already started the implementation and this would get confusing.

So please recheck your open PRs, finalize what is open and request reviews.

@Bushuo  @absurd-turtle @ThorbenStaufer @NurramoX

**Comment by markus2330** [comment]
@absurd-turtle @ThorbenStaufer @NurramoX There are still a few last use cases to be merged. Can you please update the PRs?
