### ISSUE TITLE
Improve file selector UI and responsiveness

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#1011]
### Tasks

 - [ ] Show close icon on the top right side as usual
 - [ ] Correctly render the close button as component and icon (currently manually written as button and hardcoded with letter 'x')
 - [ ] Make it responsive
 - [ ] Add (optional) title to the file selector modal
 - [ ] Improve whole layout of the modal

![file-selector_bad](https://github.com/ElektraInitiative/PermaplanT/assets/141152959/04e8ecef-1123-417b-b644-a68935622167)

![file-selector_responsive-bad](https://github.com/ElektraInitiative/PermaplanT/assets/141152959/2a5f37be-9818-4a97-941d-3997418e3604)
