### ISSUE TITLE
Enhance toolbox icons with visual indicator showing their current state

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#1025]
### Tasks

Visually indicate if a toolbox icon is currently active (enabled/available), passive (not enabled) or disabled (not available).

 - [x] Active icons, i.e. icons whose functionality is currently enabled (e.g. grid shown) or available (e.g. undo possible), are highlighted.
 - [x] Passive icons, i.e. not enabled icons, are rendered in neutral color fashion.
 - [x] Disabled icons, i.e. icons whose functionality is currently not available (e.g. redo not possible), are grayed out and disabled.
