### ISSUE TITLE
Collaboration security issues

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#1093]
### Tasks

- [ ] private maps can be accessed by everyone
- [ ] broadcaster messages are not authenticated
- [ ] propagation of additional names should be reworked. At the moment every client receives every additional name change. Maybe allow users to access all seeds on a map?

### Use case

Collaboration & Message Broadcasting

**Comment by markus2330** [comment]
@temmey this should be included in the security analysis of PermaplanT (what is written in the thesis).
