### ISSUE TITLE
Timeline: Refactor Execution of hooks

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1107]
### Tasks

 - [ ] Currently there are unnecessary method calls (e.g. scrollToIndex is executed too often) that should be optimized
 - [ ] the useEffect hook that adds event listeners is executed on every rerender
 - [ ] the hook that submits the value may need dependency on onSelectDate

### Use case

Timeline Single Selection

### Related Pull request

#1042

**Comment by Bushuo** [comment]
Imo this issue Is high priority as the Timeline currently causes the react rendering step to take ~100ms on average, which is really bad.
<img width="1672" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/9990578/e30100c4-19ee-415a-9c92-ddb46dce0b32">

@danielsteinkogler I can of course also take a look at it.

**Comment by danielsteinkogler** [comment]
@Bushuo my plan is to look into it today. if I don't manage to find a solution today i will ping you,
