### ISSUE TITLE
Add key combinations for map geometry editor

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#1112]
### Tasks

 - [ ] Key combination for making geometry points draggable
 - [ ] Key combination for adding geometry points
 - [ ] Key combination for removing geometry points

### Related Pull request

#1085
