### ISSUE TITLE
Drawing Layer: Transform Shapes

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#1126]
### Tasks

 - [x] Shapes can be selected
 - [x] Selected shapes can be resized
 - [x] Selected shapes can be moved
 - [x] Selected shapes can be edited (e.g. change color)

### Use case

Drawing Layer

**Comment by markus2330** [comment]
Editing should be like with plants: attributes should be in the left bottom toolbar. Probably this is an issue by its own, similar to #476.
