### ISSUE TITLE
Missing error messages for react query hooks/mutations

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1136]
### Tasks

 Some queries and mutations, are still missing toast messages.
 Those are marked in the code via a TODO

 - [x] add error message to `useReenableTour()`
 - [x] add error message to `useCompleteTour()`
 - [x] add error message to `useRelations()`
 - [x] add error message to `useMap()`
 - [x] remove autoclose (especially for duplicate maps)

### Related Pull request

#1118

**Comment by markus2330** [comment]
Thank you for creating the issue! I think we can also do this later.
