### ISSUE TITLE
area of plants left-overs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1154]
### Tasks

- [x] area of plants should have round edges
- [x] resizing via dragging of edges must also work non-proportional
- [x] visualization lines of good/bad neighbors in areas broken
- [x] amount indicator is not next to cursor
- [x] amount indicator should be slightly transparent (so that you can see through and align with other fields)
- [x] resizing should again show the amount indicator
- [ ] move use case to done

not so important:

- [x] left bottom toolbar should indicate that this is an area with N plants
- [x] logo in the middle or as pattern
- [x] rotation places plant label wrongly (maybe separate issue?)

### Use case

area of plants

### Related Pull request

#1149
#1160

**Comment by Bushuo** [comment]
@markus2330 there is another branch that I am working on, that fixes a couple of this issues. I will push it today.

**Comment by markus2330** [comment]
Thx! There is no hurry though, tomorrow I am off.

**Comment by markus2330** [comment]
We added:

- [ ] area of plants should have round edges
- [ ] resizing via dragging of edges must also work non-proportional

**Comment by Bushuo** [comment]
@markus2330 
I updated the PR. It is not ready yet, as I want to refactor at least the transformer out of the other stores and components.
There is a lot of places where it is used and I want to define a uniform interface for it.
My idea was, it is responsible for selections and transformations of konva nodes, a low level abstraction.

**Comment by Bushuo** [comment]
@markus2330 e2e tests are failing. I will fix them later, I hope you can review anyway.

**Comment by markus2330** [comment]
Great job, we like it. But one new bug was introduced: amount indicator is not next to cursor (I added the item above). It seems to be related to zoom level.

So only 3 left-overs now! :rocket: 

Btw. Do you get my emails? :ghost:

**Comment by Bushuo** [comment]
@markus2330 
I am glad you like it. I fixed the cursor bug.

> Btw. Do you get my emails? 👻

Sorry. I have not checked my TU account recently.
I read it now and will answer shortly, with a new email address that I regularly check.

My TU mail is about to expire as well.
