### ISSUE TITLE
shade layer usability improvements

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1161]
### Tasks

 - [ ] place color of shading on the left in text of button (large rectangle)
 - [ ] while placing shading, button should be highlighted
 - [ ] while placing text should include which shading area gets placed
 - [ ] ESC should end shade placement
 - [ ] proper validation of dates https://github.com/ElektraInitiative/PermaplanT/pull/1135#issuecomment-1891525528
 - [ ] Deleting a shading while in "Move / Add / Delete shading point" mode, should also exit that mode.
 - [ ] It would be nice if moving a point of a shading would updates its edges in real time.

### Use case

shading layer

### Related Pull request

#1135

**Comment by markus2330** [comment]
@badnames please tick in the top post what is already done.
