### ISSUE TITLE
Landing Page Improvements

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1162]
### Tasks

- [x] add blog entries (as in Nextcloud)
- [x] "Wähle aus über 8.500 Pflanzen" --> "**10.000 Pflanzen**"
- [x] "um eine schöne und reichhaltige" --> "**um eine bunte und reichhaltige**"
- [x] "Zieh deine ausgewählten Pflanzen in deinen individuellen Garten und erhalte sofortiges Feedback für ihre besten Standorte - bis zu 7 Jahre zurück und in die Zukunft!" --> "**Platziere deine ausgewählten Pflanzen in deinem individuellen Garten und erhalte sofortiges Feedback für ihre besten Standorte - ohne zeitliche Einschränkung.**"
- [x] "Teile deine Erfolge und Herausforderungen" --> "**Teile deine Erfolge, Herausforderungen oder Fotos**"
- [x] Bei Team: Jobbeschreibungen ins Deutsche übersetzen
- [x] Bei News-Artikel: "Yvonne Markl Permaculture Expert" -->  "Yvonne Markl Projektleiterin, Permakultur Expertin"
- [x] "Preisgestaltung" --> "**Preisgestaltung 2024**"
- [x] Reguläre Mitgliedschaft anheben auf **59€**; Fördermitglied auf **119€**; Permacoins auf **59**.
- [x] add to team: Jannis Adamek [Software Engineer]
- [x] add to team: Dr. Christoph Höfer [Permaculture Expert]
- [x] add to team: Daniel Steinkogler  [Software Engineer]
- [x] Reihenfolge Team: Yvonne, Markus, Paul, Christoph (du), Daniel, Jannis, Moritz, ..., Pavlo, Dr. Christoph Höfer [Permaculture Expert]

not needed:

- [ ] Bei Team: Aktive Mitglieder wie bisher anzeigen, inaktive bei ausklappen anzeigen
- [ ] Beim Blog: 2 Elemente anzeigen, die anderen mit Klick auf rechten Pfeil anzeigen

### Use case

landing page

### Related Pull request

#1164

**Comment by chr-schr** [comment]
@markus2330 
Not sure about some of the job description translations. I would not translate "Security Analyst" and "DevOps" into German

@danielsteinkogler / @horenso 
Can I hand off the last two tasks to either one of you?  😄 
I'm not experienced enough in react to do them.

**Comment by markus2330** [comment]
> Not sure about some of the job description translations. I would not translate "Security Analyst" and "DevOps" into German

It is fine not to translate them.

The other two asks are actually not urgent, it also looks great as it is.

So we can get the PR done with the little changes requested in the review.
