### ISSUE TITLE
Drawing Layer Left-Overs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1230]
### Tasks

 - [ ] Rotate of Polygon cannot be undone
 - [ ] Cannot add points in the middle of the polygon
 - [ ] close option for lines (always enabled for fill)
 - [ ] improve usability of "Filled", maybe dropdown?
 - [ ] delete points of polygon does not remove bezier helper points (leading to curved line)
 - [ ] fix texts ("du")

### Use case

drawing layer

### Related Pull request

#1221

**Comment by danielsteinkogler** [comment]
What exactly is meant by 'close option for lines (always enabled for fill)'?

**Comment by markus2330** [comment]
With option is meant a check-box or actually even better a drop down box with three options:

- open lines (like it currently is by default, the lines stay as drawn)
- **closed lines** (when finishing the lines, the endpoint automatically connects with the first point)
- filled areas (this option is currently implemented as check box)

**Comment by danielsteinkogler** [comment]
@markus2330 would it be okay to disable rotation for the bezier polygons for now?
i think its not that easy to place the lines in edit mode correctly after rotation.

add what is meant with "Cannot add points in the middle of the polygon"? Do you mean to add a point between 2 others?

**Comment by markus2330** [comment]
> would it be okay to disable rotation for the bezier polygons for now?

Yes, is fine.

> add what is meant with "Cannot add points in the middle of the polygon"? Do you mean to add a point between 2 others?

Yes.
