### ISSUE TITLE
Shading Layer Left-Over

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1231]
### Tasks

 - [ ] Cannot move or resize shading areas (handle disabled?)
 - [ ] Cannot remove points if overlapping area exist
 - [ ] Cannot read Shading Type (white on white?)
 - [ ] "couldn't load the image" if it is shown when heatmap is shown
 - [ ] heatmap should be layer
 - [ ] undo on multi-select doesn't work (only for one element)

### Use case

shade layer

### Related Pull request

#1135

**Comment by badnames** [comment]
> Cannot read Shading Type (white on white?)

Should be addressed in #1229

**Comment by markus2330** [comment]
> To my knowledge the same issue currently exists on the plant layer.

It works and it is easy to try out.

> The reason for this is that we don't have a mechanism for dispatching multiple actions as a group

Backend supports patch for arrays of plant actions and this should be added for the other endpoints, too (by the backend team).

>  This has not yet been implemented for simplicity, but it would certainly be beneficial from a UX perspective.

Hopefully this gets easier (without individual effort per layer) after frontend refactoring. We talk about this on Tuesday.
