### ISSUE TITLE
Plant hierarchy: Icon concept

### ISSUE THREAD

**Issue by chr-schr** [ElektraInitiative/PermaplanT#1310]
### Tasks

 - [ ] New icon column for plants 
 - [ ] Plant icon should be sent to the frontend (as a path / filename). Empty path means no icon - use default / fallback icon.
 - [ ] Icons will be passed down from higher ranks to lower ranks if no icon is set below, similar to other attributes. E.g. it should be possible to set one icon for all pumpkin variety / cultivars by setting it at the species level.
 - [ ] Should be able to define icons at any rank with scraper overrides

**Comment by markus2330** [comment]
Perfectly written!

Is there any difference in behavior of the icons column compared to the other columns?
