### ISSUE TITLE
Copy & Paste: Within the Same Map (using key combinations)

### ISSUE THREAD

**Issue by andreicristian97** [ElektraInitiative/PermaplanT#1321]
## Use Case: Copy & Paste

The user can copy and paste a selection of elements, including succeeding crops, within one map.

## Steps/ sub-tasks:
- [ ] CTRL-C copies current selection
- [ ] CTRL-V pastes copied selection at the user's last click
- [ ] If after copying the user did not click anywhere else, the selection is pasted with an offset
- [ ] Multiple "paste"s are inserted with offset to one another
- [ ] If other elements are selected in the meanwhile, the paste is done with an offset to the new selection
- [ ] Trying to paste into the wrong layer raises a warning.
- [ ] CTRL-C with no selection has no result
- [ ] After successful copy of selection, CTRL-C with no selected elements does not reset what was copied
- [ ] "Undo" functionality can revert the pasting

## Task linking
Tasks following this one:

- 
-

Link to documentation:

**Comment by markus2330** [comment]
Thx for creating the issue! :heart: 

> including succeeding crops

probably should be in extra issue
