### ISSUE TITLE
Copy & Paste: Icons

### ISSUE THREAD

**Issue by andreicristian97** [ElektraInitiative/PermaplanT#1322]
## Use Case: Copy & Paste

The user can copy and paste a selection of elements, including succeeding crops, by using the appropriate icons in the toolbar

## Steps/ sub-tasks:
- [ ] Add new Icons to the toolbar
- [ ] Icons and keybinding should be interchangeable (keep behavior consistent)
- [ ] Icons should be enabled/disabled based on selection or if something was copied

## Task linking
Task blocked by:

- https://github.com/ElektraInitiative/PermaplanT/issues/1321

Tasks following this one:

- 
-

Link to documentation:
