### ISSUE TITLE
Copy & Paste: Between maps of different users

### ISSUE THREAD

**Issue by andreicristian97** [ElektraInitiative/PermaplanT#1324]
## Use Case: Copy & Paste

The user can copy and paste a selection of elements, including succeeding crops, between his own map and a map of another user.

## Steps/ sub-tasks:
- [ ] Copy is done in one map, Paste in another map.
- [ ] Behaviour scenarios should be consistent with the action being done in a single map.
- [ ] There might need be some checks if copying and/or pasting is allowed in the map.

## Task linking
Task blocked by:

- https://github.com/ElektraInitiative/PermaplanT/issues/1321

Related tasks:

- https://github.com/ElektraInitiative/PermaplanT/issues/1322
- https://github.com/ElektraInitiative/PermaplanT/issues/1323

Link to documentation:
