### ISSUE TITLE
decisions

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#2]
## soon

- [ ] rss generator (Gabriel)
- [ ] #382 offline vs. collaborative: undo/redo etc. (Paul)

## to have a look at:

if this is easily possible, we will:

- [x] #375 contact form sends email via backend (smtp in rust) https://docs.rs/mail-smtp/latest/mail_smtp/ (Gabriel)
- [ ] membership onboarding via keycloak (Thorben)

## probably decided

- [ ] have cron jobs within PermaplanT backend (Gabriel)
- [x] #391 logging of incoming actix requests and diesel SQL statements (Gabriel)

## done

- [X] #30  state management & main architecture pattern
- [x] #128 frontend documentation
- [x] #101
- [x] #26 database (@aidnurs et al.)
- [x] Diesel PostGIS documentation (@NurramoX)
- [x] translations (enum and frontend)
- [x] auth/login OAuth client Rust libs (Gabriel)
- [x] #172 diesel async
- [x] Nextcloud as OAuth server? (@absurd-turtle)
- [x] #130 
- [x] #131
- [x] #170
- [x] which programming language
- [x] which drawing lib
- [x] which other libs?
- [x] REST
- [x] API blueprint
- [x] Testing framework
- [x] ORM engine https://diesel.rs/ and https://lib.rs/crates/postgis_diesel?
- [x] frontend zusammenbauen? (build tool)
- [x] type-safety between Rust and Typescript

**Comment by markus2330** [comment]
Great work so far! I added three more decisions to be done (REST+API blueprint+Testing framework). Let us discuss today who will work on that.

**Comment by buenaflor** [comment]
> * Testing framework
After further research and from some little experience I have it seems [Jest](https://jestjs.io/) is a common standard for testing for React apps and it is also a [recommended](https://reactjs.org/docs/testing.html) tool by React. I don't think a decision here is necessary, what do you think?

**Comment by markus2330** [comment]
I agree, no decision is needed but there should be a short documentation about the testing strategy.

**Comment by buenaflor** [comment]
Sounds good to me!

> API Blueprint

Can I get more context on API Blueprint please, do you mean [this?](https://apiblueprint.org/)

**Comment by markus2330** [comment]
Exactly, then we can use like https://apiblueprint.org/tools.html e.g. for testing in the CI.

**Comment by buenaflor** [comment]
I see, it is not needed then for now I suppose?

Do you have a suggestion on how in-depth the testing strategy documentation should be/what it should include?

**Comment by markus2330** [comment]
Yes, if you document the API properly as code comments it is fine by me, too.

> Do you have a suggestion on how in-depth the testing strategy documentation should be/what it should include?

It doesn't need to be very in-depth, it should mostly cover:

- what should be unit tested in frontend and backend
- integration tests, e.g. for REST API (see also https://actix.rs/docs/testing/)
- how to do manual tests for everything together
 
At the moment very rough description are enough, as we are not finished with the use cases yet.

**Comment by markus2330** [comment]
Someone told me about https://github.com/tauri-apps/tauri/issues/1514 (Tauri itself might also be interested in the long-term), which discusses type-safety between Rust and Typescript. There seem to be quite a few options:

- https://rspc.dev/overview/ (works with a Rust backend and Typescript frontend)
- https://trpc.io/ (older then rspc)
- https://crates.io/crates/typeshare (supports Typescript)
- An example how it could be: https://github.com/oscartbeaumont/tauri-specta
- https://github.com/Aleph-Alpha/ts-rs
- https://github.com/tauri-apps/tauri-bindgen

Can you please write up a decision, even if we decide to not do anything of it.

**Comment by markus2330** [comment]
The main architecture pattern for the frontend is also to be decided, e.g.:

- https://redux.js.org/
- https://reactjs.org/blog/2014/05/06/flux.html
- https://www.evozon.com/model-view-viewmodel-in-reactjs/

The decision will also influence how undo is done, e.g. by using https://www.npmjs.com/package/redux-undo-redo-middleware?

**Comment by markus2330** [comment]
If we are using JSON schema, another option would be: https://imfeld.dev/writing/generating_typescript_types_from_rust
(If not, direct ways are preferable.)

**Comment by buenaflor** [comment]
I played around with a bit and it seems like [typeshare](https://crates.io/crates/typeshare) is the one that works the best seamlessly, it is also easy to configure so I'm leaning towards using it

**Comment by markus2330** [comment]
LGTM, too.

**Comment by markus2330** [comment]
@buenaflor if you want to look into graphql anyway, it would be nice to have a short write-up what you found in a decision. (If you don't look, don't write :wink:). Some libs seem to be a bit immature but there already seems to be everything needed:

- https://typed-graphql-builder.spion.dev/ (alternative to https://tql.dev/) for type-safe code in frontend.
- https://github.com/graphql-rust/juniper
- Example how it could be done: https://github.com/husseinraoouf/graphql-actix-example or https://github.com/nenjotsu/rust-actix-graphql

It is not totally unrealistic that for lookups in the map REST is not ideal (slow).

**Comment by markus2330** [comment]
We got very positive feedback about our decisions: "React + Vite + TypeScript klingt gut, das ist aktuell der populärste & stabilste Stack für Frontend Projekte"

For State Management, however, we should look into:

- Recoil/Jotai
- React Query

I updated the top post.

**Comment by absurd-turtle** [comment]
There is already a small state-management solution in use. It's called zustand. If we switch to a different library we should get rid of this dependency.

**Comment by markus2330** [comment]
@absurd-turtle exactly, that is what is to be decided. See https://github.com/ElektraInitiative/PermaplanT/pull/30 for prior work, I think you can take over the work on this PR.

**Comment by markus2330** [comment]
@ElektraInitiative/permaplant
I tried to add all decisions at the top post (including the ones we discussed in the Backend meeting). Are there any other decisions
- we need to decide upon or
- are already open and not linked above?

If you want one of them assigned, please write here.

**Comment by kitzbergerg** [comment]
@markus2330 about the rss generator: What should I write there and where?
There is a crate [rss](https://docs.rs/rss/latest/rss/) which can be used. As far as I understand we would need to put articles (or whatever else we want to serve) in the database and sort by date when querying. Maybe also provide pagination. Then we a requests come in we query and parse the db struct to the [rss Channel](https://docs.rs/rss/latest/rss/struct.Channel.html). So Channel would be kind of like a DTO in this case and the db struct is separate.
Apart from that we have to think about how to insert into the RSS and that we have to serve the data as xml instead of json.

However there isn't really a decision involved. It is more 'How to implement a RSS generator' so it doesn't really fit in decisions.

**Comment by markus2330** [comment]
The idea was to have some Markdown file (or something else easy to write manually) that is used for both:

1. to generate the news in the frontend
2. to generate an RSS feed

Ideally we would use something that already fully implements this, which doesn't seem to exist in Rust.

@absurd-turtle can you maybe share your idea? Would the backend be involved? Is there some ready-made solution.

**Comment by absurd-turtle** [comment]
I think the best solution is to generate the RSS feed in the backend and serve the XML on a specific endpoint.
Then have a separate endpoint for the blog posts to serve the data in json to the frontend.

To store the data we could just have files that are served directly or put it in the database.
If we store the data in the database we would also need some UI/cli for the author to put the new post there.

**Comment by markus2330** [comment]
@absurd-turtle As the news feed on the web site should now be a NC chat, it would be great if we can generate the RSS feed from the chat's content. Is this better implemented in the frontend or in the backend?

**Comment by markus2330** [comment]
We could try to use

- https://nextcloud.com/blog/bridging-chat-services-in-talk/ i.e.
- https://github.com/42wim/matterbridge
- https://mattermost.com/marketplace/rssfeed-plugin/ or (probably better)
- https://matrix.org/docs/projects/bot/matrix-rss-bridge

But it is a bit much technology involved but maybe okay for a public announcement channel. Having our announcement channel in many formats is not a bad thing.
