### ISSUE TITLE
deploy mdbook+storybook documentation

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#275]
As part of #158 we should also build and deploy our documentation.

This include 3 parts:
- general documentation built using mdbook (see #180)
- storybook (frontend documentation)
- backend code documentation (see below)

To build the backend code documentation you can run `cargo doc` in `backend/`.
The output can be found in `target/doc/`.
See [here](https://doc.rust-lang.org/cargo/commands/cargo-doc.html) for further reference.

To build the general documentation run `mdbook build` in the projects root. For that Rust has to be installed as well as mdbook  and the preprocessors. This will automatically generate documentation out of our `doc/` folder.
```bash
cargo install mdbook mdbook-mermaid
cargo install --git https://github.com/ElektraInitiative/mdbook-generate-summary mdbook-generate-summary
mdbook build
```
The output can be found in `book/`.
This has to run when code changes in either `book.toml` or `doc/`. Note that it might fail so there has to be validation in PRs.
There already is a Dockerfile for mdbook in ci.

Afterwards the documentation should be deployed and served.

**TODOs**:
- [x] validate backend code doc in PRs (already done)
- [ ] build backend code doc (master only)
- [ ] deploy and serve backend code doc on a public URL (master only)
- [x] validate general doc in PRs (meaning `mdbook build` might fail if e.g. there is a missing README.md in a directory)
- [ ] build general doc (master only)
- [ ] deploy and serve general doc on a public URL (master only)
- [ ] describe where documentation can be found in the projects root README (add links to public URLs). This should include backend code doc (=rustdoc), general doc (=mdbook) and API doc (=swagger).

@lukashartl You can start as soon as #180 is merged.
@markus2330 Fell free do add suggestions.

**Comment by kitzbergerg** [comment]
The steps to deploy shouldn't change (apart from maybe an additional preprocessor). So I would prefer adding it to CI as in my opinion there is no real disadvantage and everybody can get a feel for how it behaves. 

At least I thought the whole point of merging it now is that we finally have documentation everybody can easily access. Changing it later like reordering items or adding additional doc won't change the behaviour of the book.

**Comment by markus2330** [comment]
> So I would prefer adding it to CI as in my opinion there is no real disadvantage and everybody can get a feel for how it behaves.

Of course, everyone would prefer it but there is a big backlog in CI tasks and some of them are very severe and urgent. E.g. we cannot test the seed use case because the data is still not imported, see #211. There are people waiting for the release, which also cannot be done because the release pipeline is not ready. So please be patient here.

> At least I thought the whole point of merging it now is that we finally have documentation everybody can easily access. 

No, it is about being able to do the PR next week (improving documentation). I don't think it is a problem to run it locally.

**Comment by markus2330** [comment]
@kitzbergerg you said you update the issue a bit, is this already done? What are the changes you propose?

**Comment by kitzbergerg** [comment]
> @kitzbergerg you said you update the issue a bit, is this already done? What are the changes you propose?

It is done. There were no real changes, just updating the description so it is easier to follow.
