### ISSUE TITLE
Photo Layer

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#387]
**usecase:** [Photo Layer](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/assigned/photo_layer.md)

**depends on:** #381 and #380 

- [ ] load images from Nextcloud, see #475
- [ ] upload new image, see #475
- [ ] create Object with existing image from Nextcloud
- [ ] ~~create Nextcloud Talk conversation when adding a new Image with circle Id (requires circle creation on Map creation, adding new Members to circle when adding new Members to map)~~
- [ ] image comments component #539 
- [ ] ~~display/poll messages from conversation~~
- [ ] ~~send Message to conversation~~
- [ ] remove Image
- [ ] ~~remove corresponding conversation in Nextcloud~~
- [ ] prompt user to take photo and upload
- [ ] create preselection in Nextcloud with emoticons
- [ ] Check permissions for deleting images
- [ ] synchronize layer state with backend

**Comment by markus2330** [comment]
I created a subtask for the first two items as it is urgently needed for base layer #475. Not necessarily the component is urgent but that the whole NC image functionality gets better tested and fixed (CORS etc.)
