### ISSUE TITLE
Plant Layer Visual Indiciations

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#435]
## visual indications

- [ ] generate heat map from following criteria:
    - plant relationships at location 
    - zone
    - pH value
    - moisture
    - animals
    - shadows

- [ ] plant relationship lines:
  - while dragging the plant onto its location lines to nearby plants should be shown
  - the line color indicates the relationship to the selected plant (red: antagonist, green: companion, grey: neutral/no data) (could be a FLOSS issue depending on priority)

## How should it work?

The user adjusts relationships as needed.

- [ ] generate warnings

## basic features

- [x] plant element #436
- [x] move elements #436
- [ ] edit plant data  #476
- [ ] remove plant from map (when plant died, was harvested, etc)  #476
- [x] delete plant (deletes plant from database) #436

## suggestion groups

- [x] frontend: #436

filter all:
- [x] filter plants for current season (selected time of year) #453 

groups:
- [x] available seeds
  rank/sort:
  - [x] early seed expiration date first

**Comment by markus2330** [comment]
I've split less urgent tasks to  #443 and changed above to `- [ ]` so that you can more easily track what is already done.

**Comment by markus2330** [comment]
Btw. in discussion with @buenaflor in #357 we agreed that "Drag&Drop" might actually be not needed or even be a disadvantage when a user wants to create an area of plants. So better to simple click, and then click again for placing or holding click for creating area.

**Comment by markus2330** [comment]
I moved visual indications on top and renamed the issue accordingly. I extracted plant attributes to  #476

**Comment by Bushuo** [comment]
@markus2330
The current solution in #603 is not great on performance I guess, but with the moving lines there is not much to do about it.
Another solution for indicating a relationship could be an outline or border around the plantings.

Like this:
![Image](https://github.com/ElektraInitiative/PermaplanT/assets/9990578/b7d8b73f-d0eb-4fd3-b35c-c46b9421f5b0)
