### ISSUE TITLE
Fix Remaining Broken Links

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#558]
### Use case

none

### Related Pull request

#554

### Tasks

- [ ] moisture layer is now called doc/usecases/assigned/hydrology_layer.md
- [ ] the links outside of doc: why is the doc folder the root?
- [ ] Enable warning-policy = "warn" inside `book.toml` and fix all warnings.

**Comment by markus2330** [comment]
Btw. probably also reorder: first tasks, then use cases then related pull requests.

**Comment by 4ydan** [comment]
Some broken links got in again with the last merges, will fix them.

**Comment by 4ydan** [comment]
Working on a fix right now.
