### ISSUE TITLE
Entrybarriers

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#560]
### About

The entry barries are already pretty low. It is just some minor things that I would want to improve for new people coming into this project and our future selfs.

- First reduce the overall number of actions that have to be performed to start the backend, frontend or just to create the docs.
- Give a Dockerfile or/and docker-compose file that describes the environment, so people can either run it or mimic the enviroment.

Right now the "truth" exists in multiple files spread (backend/01setup + build-scripts/Dockerfiles( in /ci folder)). It would be great if the code is the documentation and the README for the backend/frontend just says to run `make` for example, start the devcontainers or have a look at the Dockerfile and adapt the host system to it. Also using the code as documentation makes sure it works, a readme can get outdated/broken easily and might get forgotten to be updated.

This way also the backend team doesnt work on a separate readme and the ci team on separate scripts. If we can make both utilize the same Makefile, work can't diverge and its easier to maintain.

### Related Pull request

#549 #552

### Tasks

Reduce overall number of actions that have to be performed:
 - [ ] to start the backend
 - [ ] to start the frontend
 - [ ] to build/run the mdbook/storybook
Further:
 - [ ] Unify documentation and code
 - [ ] Simplify backend setup docu
 - [ ] Update development_setup.md
 - [ ] Give a Dockerfile for developing
