### ISSUE TITLE
correct formatting of plant names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#583]
### Tasks

All places where plant names are written following syntax/format should be used

 - [ ] start with English name (later German, to be implemented)
 - [ ] then open parenthesis (
 - [ ] then unique name in italic
 - [ ] except of cultivar, which is in `'single quotes'` but not italic
 - [ ] then close parenthesis )

See also doc/database/hierarchy.md

### Use case

plants layer

### Related Pull request

#579

**Comment by temmey** [comment]
Hey @lukashartl , given my limited expertise with React, I'd value your opinion on a solution I'm proposing. My plan involves creating a new `utils/ExtendedPlantsSummaryDto.ts`. This would extend the existing PlantsSummaryDto with a new property called DisplayName for now.

Looking ahead, I anticipate more instances where we'll need to extend the functionality of the PlantsSummaryDto(and maybe others?). In these cases, my idea would be to load it directly into the MapStore handler.

What are your thoughts on this approach?

**Comment by markus2330** [comment]
@Bushuo is the right person to ask this (lukashartl is infrastructure/server/CI, see also authors.md)

**Comment by Bushuo** [comment]
I would probably create a class that implements this dto and use instances of the class instead of the dto.
React Query has a handy feature for this

```ts
// data is a new Instance here
const {data} = useQuery({
  queryKey: [...]
  queryFn: () => loadPlant(...),
  select: (data) => {
    // select can be used to transform the data returned from the query function
    return new Instance(data)
  }
})
```

**Comment by markus2330** [comment]
@temmey what is the current status? Can you please create a PR? This would be very important to have for the user study.

**Comment by markus2330** [comment]
follow-up is #693
