### ISSUE TITLE
further makefile targets

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#608]
### Tasks

pure convenience, not important:

 - [x] diesel database reset
 - [x] diesel migration run
 - [x] redo migrations, see also #134 
 - [x] scraper insert

### Related Pull request

#549
