### ISSUE TITLE
data-testid: improve naming scheme

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#611]
There are some missing locators.
See doc/guidelines/frontend-locators.md for more information about locators.

### Tasks
- [x] Update locator guidelines to reflect naming schema (component + name)

#### (Paginated) Selectboxes:
- [x] Seed creation page both select boxes

#### Navbar:
- [x] Language selector

#### Map create page
- [x] Set location button
- [x] The privacy select box

#### Map management page
- [x] It would be nice if each map could be accessed with a locator instead of with text right now

**Comment by markus2330** [comment]
Thanks for raising the issue!

Can you maybe create a CI check that verifies all elements have ids?

**Comment by 4ydan** [comment]
I am not sure if I should wait with everything being refactored first before I write the tests. Maybe I should also do that myself?
We already had #706 and now I have issues accessing the radio buttons in my tests.
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/f0195f93-d3b5-46e1-b261-25144d1167e1)
Also refactoring tests later when locators are changed is also something that has to be done.

**Comment by markus2330** [comment]
You can also refactor while writing tests. But to not have all the work load on you, I think we should finish #653 and advertise it tomorrow in the meeting.

**Comment by markus2330** [comment]
@4ydan is here still something to be done?

**Comment by 4ydan** [comment]
There is surely some missing locators, I will update the top post.

**Comment by markus2330** [comment]
Ok. Isn't it better to simply extend locators as needed for E2E directly within the PRs implementing E2E tests?

**Comment by 4ydan** [comment]
> Isn't it better to simply extend locators as needed for E2E directly within the PRs implementing E2E tests?

We should probably decide on whos job it is to write these locators, maybe pass this responsibility to the e2e test writer and mention it in the guidelines?

**Comment by markus2330** [comment]
Yes, I am okay with 

- everything that helps you and
- what we can
  -  clearly ask for using guidelines and
  - check in reviews.

**Comment by markus2330** [comment]
@badnames if possible, please help @4ydan

**Comment by markus2330** [comment]
Is this done?

**Comment by 4ydan** [comment]
No, the top post is still reflecting the missing locators.
Language selector is #904

**Comment by markus2330** [comment]
@4ydan can you maybe tell @badnames which locator you want where?

We also should update the frontend locator guidelines so that it is less prone to non-uniqueness, maybe as suggested by @tschawax.

**Comment by 4ydan** [comment]
@tschawax 
So what is your final suggestion on `data-testid`'s? How do you wanna name them consistently? Should every class on top have a const Object storing all `data-testid`'s? What is the benefit of that? Why are the other id's stored in an Object (`id` / `data-tourid`)?

**Comment by 4ydan** [comment]
I did not have any preferred way of doing it, it is good to have your experience on this topic.
Thank you for the clarification, I totally missed that the objects were used in the tests. This makes totally sense now. I also like the notation.

**Comment by 4ydan** [comment]
What about dynamic test id's. 
For example the results of plant search:
```
<li
  className="my-1 flex"
  data-testid={`${plant.common_name_en} ${plant.unique_name}-plant-search-result`}
>
```

These names can not be fully frozen into objects. Do we just live with that?

**Comment by 4ydan** [comment]
Also you have coded the id `search-input__search-input` into the component SearchInput. What if there are multiple SearchInputs on the page, arent the id's same then or do I miss something?
For example we have the `BaseLayerRightToolbar` feature which implements multiple `SimpleFormInput` components. In this case we are passing the data-testid's from the `BaseLayerRightToolbar` feature into the `SimpleFormInput` component and provide a more detailed id to distinguish between both inputs. This is only possible because there is no data-testid already set inside `SimpleFormInput`
