### ISSUE TITLE
document coordinate system

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#635]
### Tasks

- [ ] where is 0,0 in frontend, ...
- [ ] where do x,y increase (up, left)...
- [ ] 1px = 1cm
- [ ] granularity of heatmap

### Related Pull request

#566
