### ISSUE TITLE
shade layer endpoint

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#638]
### Tasks

 - [ ] create table for shade layer
 - [ ] create end point that allows to add, edit, move and remove and delete areas/polygons where and how much shade is (matching to enum existing already for plants)
 - [ ] use shade layer in heatmap

### Use case

shade_layer
