### ISSUE TITLE
identifier for i18n and tests

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#639]
### Tasks

@Bushuo wrote in #613
> Going forward, this all seems pretty overkill.
> Maybe the refactoring/maintenance burden is not that high and we really just use some simple ids (with data-testid).

Yes, I agree, it is overkill. Let us keep it as simple as possible, `data-testid` (and directly using Text in certain situations) is the more straight-forward way.

What about using the same guidelines for both i18next identifiers and `data-testid`?

Background: There are already some inconsistencies in the  i18next identifiers:

 - [ ]  do error_ prefixes, other as postfixes  in i18n/en/common.json (I think we should go for prefix)
 - [ ]  sometimes camcase, e.g.sliderTooltip) in i18n/en/layerSettings.json (I think it should be slider_tooltip)
 - [ ] "title" and "button" sometimes prefix, sometimes postfix, sometimes hierarchy e.g. i18n/en/maps.json (I think it should be hierarchy or prefix)
 - [ ] sometimes failed and not error: i18n/en/nextcloudIntegration.json load_image_failed
 - [ ] sometimes button, sometimes btn i18n/en/seeds.json (I think we should use full words, i.e. button)
 - [ ] sometimes uppercase i18n/en/undoRedo.json (CREATE_PLANT -> create_plant)

@Bushuo @4ydan what do you think?

### Use case

translation

### Related Pull request

 #613

**Comment by 4ydan** [comment]
We both just had a call on discord and we agreed on using testid's. As already mentioned by bushuo interpolation is a big problem and won't allow us to use the jsons consistently. I am also not a fan of mixing stuff, even though it would be really handy to use the jsons and search everything by text. Worst case, when someone breaks a test, because of changing an error message or button text, he/she can easily go and modify the according test object. But this case should be very rare as the texts should be final and reviewed before we write tests for them.

**Comment by markus2330** [comment]
Decisions are either in consent (everyone obviously agrees or doesn't care) or by written decisions (especially for more important stuff where it is important to get the decision right).

Anyway, please read the text above carefully. My idea actually is to use testids (data-testid), and describes a naming convention for them.

> But this case should be very rare as the texts should be final and reviewed before we write tests for them.

No, the text is far away from being final. It was written and reviewed by computer scientists with little detailed feedback from real users yet. Thus texts (other than "Submit") are very likely to be changed.

**Comment by 4ydan** [comment]
> Decisions are either in consent & please read the text above carefully

I agree, when two people agree on something, it doesn't mean that everyone agreed on it. I just wanted to point out, that we two are not fans of using json parsing, as long as interpolation is in our way.

From my point of view, the internationalization should not have an effect on the tests. When I perform tests, I want to purely focus on the functionality. I have no experience with i18n. This is all new to me and I don't understand the problems that you currently have with it.

> What about using the same guidelines for both i18next identifiers and data-testid?

Does a guideline for i18next exist? I couldn't find one. Or does this mean as in write them both now so they are the same.

> No, the text is far away from being final. 

The texts I am referring to are info/error popups and user interactable elements. These should be final if they can't be, we should not use texts.

> My idea actually is to use testids (data-testid)

What exactly is the difference between testid and data-testid?

**Comment by markus2330** [comment]
> Does a guideline for i18next exist? I couldn't find one. Or does this mean as in write them both now so they are the same.

There is some documentation about i18n (very well hidden) in ./doc/contrib/frontend.md but there is only little guidance about the identifiers.

> The texts I am referring to are info/error popups and user interactable elements. These should be final if they can't be, we should not use texts.

I don't know what you mean here? If you talk about testing: Yes, for testing data-testid is more stable than searching for text. It is a bit more effort, though.

> What exactly is the difference between testid and data-testid?

I used it: General concept vs. specific attribute to use. But better we only use `data-testid` from now on as it seems to be clear that we want to use it.

**Comment by 4ydan** [comment]
> I don't know what you mean here?

Lets define action/user interactable elements

Action: text inputs, checkboxes, radio buttons, select options, mouse clicks, type characters, keys and shortcuts as well as upload files and focus elements.

For me it is important to find the action elements. If its by text, the text better be final, if not, I will use the `data-testid`. But in general, the action elements text should be final, as most of the time it's some crud operation.
Everything else, that is not an action element, I'm currently not interested in testing for simplicity reasons. Can do it, once we have covered the basic stuff.

Also, using `data-testid` for all actions, would be my preferred way, since I'm not sure if all actions have a text, so why not use `data-testid` for all, what is the benefit of mixing it?.

**Comment by 4ydan** [comment]
## This is what [Playwright](https://playwright.dev/docs/api/class-page#page-get-by-role) suggests.

### [Roles](https://playwright.dev/docs/locators#locate-by-role)
> To make tests resilient, we recommend prioritizing user-facing attributes and explicit contracts such as page.getByRole()

### [Labels](https://playwright.dev/docs/locators#locate-by-label)
> Most form controls usually have dedicated labels that could be conveniently used to interact with the form. In this case, you can locate the control by its associated label using [page.getByLabel()](https://playwright.dev/docs/api/class-page#page-get-by-label).

### [Text](https://playwright.dev/docs/locators#locate-by-text)
> We recommend using text locators to find non interactive elements like div, span, p, etc. For interactive elements like button, a, input, etc. use [role locators](https://playwright.dev/docs/locators#locate-by-role).

### [Test id's](https://playwright.dev/docs/locators#locate-by-test-id)
> Testing by test ids is the most resilient way of testing as even if your text or role of the attribute changes the test will still pass. QA's and developers should define explicit test ids and query them with [page.getByTestId()](https://playwright.dev/docs/api/class-page#page-get-by-test-id). However testing by test ids is not user facing. If the role or text value is important to you then consider using user facing locators such as [role](https://playwright.dev/docs/locators#locate-by-role) and [text locators](https://playwright.dev/docs/locators#locate-by-text).

Here are the [suggested locators](https://playwright.dev/docs/input) from playwright for each action:
- text inputs: **label**
- checkboxes: **label**
- radio buttons: **label**
- select options: **label**
- mouse clicks: **role or text**
- type characters:  **locator**
- keys and shortcuts: **text or role**  **<- this is the only place where I would use text**
- upload files and focus elements: **label**

**Comment by markus2330** [comment]
Yes, good inputs. I think you can simply write the discussed guidelines and I will comment there.

**Comment by 4ydan** [comment]
Created a first draft.
