### ISSUE TITLE
Include insert_plant_relations scraper into CI

### ISSUE THREAD

**Issue by temmey** [ElektraInitiative/PermaplanT#645]
### Tasks

 - [ ] copy Companions.csv into CI pipeline
 - [ ] copy Antagonist.csv into CI pipeline
 - [ ] create Sizes.csv and copy into data
 - [ ] add `cp /nextcloud/Companions.csv ./data/` and  `cp /nextcloud/Antagonist.csv ./data/` to Jenkinsfile

### Related Pull request

#606

**Comment by markus2330** [comment]
Thanks for creating this issue! Probably you also should already copy the Sizes.csv (doesn't exist yet, simply create an empty file) to not have to touch the CI scripts too often.

**Comment by 4ydan** [comment]
The nextcloud database folder is currently not public if I remember corretly. What about creating a separate repo which contains all data/testdata?

**Comment by markus2330** [comment]
The NC folder is synced on our CI systems (folder /nextcloud)

**Comment by markus2330** [comment]
Isn't it up to date? (@lukashartl implemented this)

**Comment by 4ydan** [comment]
I will have a look at it, didn't know.

**Comment by lukashartl** [comment]
No, we currently do not sync this.
Syncing should be reconsidered when we have finished the nextcloud migration.

**Comment by markus2330** [comment]
@lukashartl thx for the quick answer. We really desperately need some infrastructure docu :sos:

**Comment by 4ydan** [comment]
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/7501d03c-869b-4f00-b024-c894cc46fedf)
Doesn't look like the file exists?

**Comment by lukashartl** [comment]
Let's discuss this in our session later today

**Comment by markus2330** [comment]
What is the outcome? Please also document what was done/discussed/learned (infrastructure or this repo as appropriate)

**Comment by markus2330** [comment]
Great, keep up the good work! :heart:

**Comment by markus2330** [comment]
I think this is done.
