### ISSUE TITLE
undo improvements

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#657]
### Tasks

 - [x] unclear if undo/redo is available (should be gray if it is not available)
 - [x] ~sometimes stays active after clicking (blue border) (is for all icons like this, should be uniformly changed)~ => this border indicates the current focus and is an important accessibility feature (keyboard navigation). it should be made less noisy, though (see next criterion)
 - [x] make focus border less noisy

### Use case

undo_redo
