### ISSUE TITLE
Makefile: improve dependencies

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#679]
### Tasks

With some added dependencies to (fake) files, we could avoid running the same targets over and over:

 - [ ] `npm install` target should depend on `frontend/package.json`
 - [ ] `install` target imho should also do `npm install` (installing frontend stuff)
 - [ ] `install` should write some fake file like `.install`, and not run again unless `.install` gets older than the `Makefile`s themselves (i.e. it should only run again when the Makefiles get updated, which might contain new installation instructions). This probably won't work with deps but needs an `if`.

**Comment by 4ydan** [comment]
Yes, I'm not very happy anymore with the current state of the makefile, since I keep getting the feeling that it replicates a lot.
I had this idea to have some self documenting code about this repo that runs/builds and tests stuff in a very minimal sense. So that new users can get started faster. 
I think some targets should be decoupled. Also I dont think people use the target install like we use it. Shouldn't install basically create a backend binary or some executable of the app?

**Comment by markus2330** [comment]
I like the Makefile very much, the reexecution is simply because of missing deps (hence this issue).

Yeah, `install` usually does something totally different but I think it is okay as `cargo` and `npm` both also call it `install`.

**Comment by 4ydan** [comment]
I thought this is not fixed, as #681 is not merged yet.

**Comment by markus2330** [comment]
No, it is not yet fixed my question was simply if everything is clear what should be done as the top-post is not really up-to-date anymore.

**Comment by 4ydan** [comment]
I thought you closed the issue by accident, so I reopened it.

>if everything is clear what should be done

Yes.
