### ISSUE TITLE
grid

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#680]
### Tasks

 - [ ] use case does not have links etc.
 - [ ] grid icon does not properly indicate if it is pressed
 - [ ] 1m legend should be right bottom and being always fixed positioned
 - [ ] 0,0 should be specially marked (e.g. cross)

### Use case

grid

### Related Pull request

#524

**Comment by markus2330** [comment]
"grid icon does not properly indicate if it is pressed" will probably be fixed by @tschawax but I think we don't have an issue for that yet?

**Comment by badnames** [comment]
> 1m legend should be right bottom

At the moment his might cause the legend to disappear, depending on the size of the browser window and the size of the left and right toolbars.
The reason for this is that our map area is not resized according to those values. 
Overflowing areas are only hidden.

Fixing this would require me to redo the styling of the BaseStage component.
This might take me a long time since I don't know how this could be accomplished at the moment.

**Comment by badnames** [comment]
> remove not needed svg

Which SVG are you talking about here?

**Comment by markus2330** [comment]
> At the moment his might cause the legend to disappear, depending on the size of the browser window and the size of the left and right toolbars.

The more important part is, that it stays fixed during panning. Does this work?

>  Which SVG are you talking about here?

The non-used one from https://github.com/ElektraInitiative/PermaplanT/pull/524/files (grid or grid-dots)

**Comment by badnames** [comment]
> The more important part is, that it stays fixed during panning. Does this work?

I will push the fix shortly.
