### ISSUE TITLE
fix plant names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#693]
### Tasks

- [x] Common name, because it is written first, should be capitalized (tomato -> Tomato)
- [x] space between common name and (Unique name) is missing
- [x] no brackets if there is no common name (but still keep it in italics!)
- [x] hovering text for plants is not yet correct: should be shown as in search

### Use case

plant_layer

### Related Pull request

#691

**Comment by temmey** [comment]
created #694 which solves all but the last task.
@Bushuo do you maybe know what branch this feature was implemented so i could cherry pick it?

**Comment by Bushuo** [comment]
@temmey Hi, this will not work, as I did this differently before.
The code for the current tooltip is in `BaseStage.tsx:245`
You could copy this one into the planting element, then make sure the original is not displayed if the "toggle all" mode is also active.
For the "toggle all" mode you can orientate yourself by how it was done in the grid layer, combine it with the visiblity prop of the label.

**Comment by markus2330** [comment]
I removed the last point

- [ ] there should be a button (toolbar) to show the hovering text for all plants (as @Bushuo already had implemented earlier), does not need to be in this PR, then create left-over

as we already have #582 for that.

**Comment by temmey** [comment]
since we merged #694 can we close this?

**Comment by markus2330** [comment]
Yes, this is fixed now.

**Comment by markus2330** [comment]
Docu should also be updated in doc/database/hierarchy.md :wink:

**Comment by temmey** [comment]
pr #770
