### ISSUE TITLE
0.3 release

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#702]
### Tasks

- [x] manually test dev.permaplant.net according to protocols #700 
- [x] run external link check (book.toml: follow-web-links)
- [x] npm audit, fix security problems
- [x] check if all milestone issues are fixed
- [x] build https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT-Release/
- [x] git tag -s vX.X.X
- [ ] git push --tags
- [ ] create release PR to pump versions and new section in Changelog
- [ ] write announcement

**Comment by markus2330** [comment]
I also added this as future documentation in #667, please feel free to comment there if you have ideas on how to improve the release procedure

**Comment by markus2330** [comment]
www.permaplant.net is successfully deployed but I did not tag the commit yet. We could still include some further small fixes (@badnames @ThorbenStaufer @Bushuo), as long as no user participated. (Once someone participated, we better pump to 3.1).

Most important to fix is #713 but please also look at others in https://github.com/ElektraInitiative/PermaplanT/milestone/4

Larger changes should not be done (and won't be merged), so that we don't introduce any new bugs.

**Comment by Bushuo** [comment]
@markus2330 I will work on it today in the evening.

**Comment by markus2330** [comment]
> I will work on it today in the evening.

Great, thank you! It is rather unlikely that we already work with a participant today, so a fixes this evening would be perfect.

@badnames thx for the urgent fix! fd6585c6b50db63f06715a68c3da6e17a46632a6 is deployed on www.permaplant.net
Looking forward to further small fixes.

**Comment by markus2330** [comment]
Btw. you are also very welcomed to feedback the tour.

**Comment by markus2330** [comment]
I now deployed 5c41142cdf1fce946a14fa99306ab0640a5fef89, it again contains several improvements of the tour texts and fixes (nearly?) everything we found with manual testing.

> Btw. you are also very welcomed to feedback the tour.

@Bushuo thx for the feedback and a even bigger thx for the fix!

I would like to get this done today, tomorrow I am not available for most of the day.

@ThorbenStaufer What is the status of #711?

@temmey What is the status of import of sizes #479? Would be great to get this in, especially if it is already done?

Please do these fixes first to get this done.

**Comment by markus2330** [comment]
I'll hopefully do the release tomorrow in the early morning. Our first participant is tomorrow 16:00.

**Comment by ThorbenStaufer** [comment]
> Our first participant is tomorrow 16:00.

Isn't our first one at 10:00? He at least registered for the 10 am. slot.

**Comment by markus2330** [comment]
dbd1dde54ae295e16cc8d321b09bcea401ccc646 now got tagged with v0.3.0

We also improved mergedDatasets.csv with many manual fixes, to be automated later. This is now also in a repository (you should have got access) and also tagged with v0.3.0

A big thanks to everyone involved in this release. Really great work with many important last-minute fixes!

> Isn't our first one at 10:00?

Yeah, looks like it someone else registered on the 10am slot. But that shouldn't be a problem, as everything is released&ready! :rocket:

**Comment by markus2330** [comment]
#733 is also merged, so it is now a good time to rebase PRs, CHANGELOG.md should now target 0.3.1

:rocket:
