### ISSUE TITLE
Improve tour

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#711]
### Tasks

 - [x] Base Layer (1/2) should be shown where Base Layer (2/2) is
 - [x] Plants Layer (1/16) should be shown where Plants Layer (2/2) is
 - [x] Tour does not show again even if you did not cancel (e.g. immediately go back)
 - [x] The tour ends with the timeline set in the future, this should be explicitly reverted (like the plantings) to not confuse the user.
 - [x] Test Protocol.

### Use case

gain blossoms

**Comment by Bushuo** [comment]
Another issue that should be fixed within this issue is
- [ ] The tour ends with the timeline set in the future, this should be explicitly reverted (like the plantings) to not confuse the user.

**Comment by markus2330** [comment]
@Bushuo Thx, great input! I fully agree. I updated the top post.

We also should have a statement in the test protocol that at the end of the tour the map is in the initial state.
