### ISSUE TITLE
changes of dates within multi-select

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#727]
### Tasks

- [x] select several plants
- [x] change date (added, removed)
- [x] delete
- [x] changes in map store to register all plants as selected
- [x] toolbar left bottom must be new component that switches between cases
- [x] selected elements are highlighted in blue to further indicate their actual selection
- [x] prefill common dates of selected plants (added, removed)

### Complexity

without ctrl+shift: 21

### Use case

Multi-Select

**Comment by markus2330** [comment]
@Bushuo this would be super-nice to have. Is it difficult to fix?

**Comment by Bushuo** [comment]
@markus2330 This is quite difficult. I seem to recall that we said it's ok that the left toolbar only shows the first selected planting in case of a multi select. Thats why we included the blue indicator for the currently selected planting.

If we add this, we need to also handle the case where multiple plantings are selected but all of them have different values vs the same value, which name gets displayed, etc.

I would not label this as a bug, but a nice to have feature.

**Comment by markus2330** [comment]
@tschawax are backend changes needed here?

**Comment by markus2330** [comment]
Yes, good idea. Let us do a straight-forward implementation and an optimization only if required.
