### ISSUE TITLE
share token spread around

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#731]
### Tasks

 - [ ] add a const variable that holds the shared token (currently 2arzyJZYj2oNnHX)
 - [ ] use it in frontend/src/features/landing_page/components/GeoMap.tsx
 - [ ] use it in ontend/src/features/landing_page/components/Teammember.tsx
 - [ ] use it in frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx
 - [ ] use it in [frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx](https://github.com/ElektraInitiative/PermaplanT/pull/729/files#diff-bbcf8846238f3f98baa4d467b245d0704212cd847639d0b3d616687c14942793)
 - [ ] use it in  frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx
 - [ ] use it in frontend/src/features/landing_page/components/BlogOverview.tsx

### Use case

nextcloud integration

### Related Pull request

 #729

**Comment by markus2330** [comment]
Probably it is not the best idea to make a dependency across all these features. And it is relatively easy to search&place all occurrences. So I'll close the issue for now.
