### ISSUE TITLE
0.3.1 release

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#740]
### Tasks

- [x] manually test dev.permaplant.net according to protocols  #743
- [x] run external link check (book.toml: follow-web-links)
- [x] npm audit, fix security problems
- [x] check/improve reformatting
- [x] check if all release-critical issues are fixed
- [x] build <https://build.libelektra.org/job/PermaplanT-Release/>
- [x] git tag -s vX.X.X
- [x] git push --tags
- [x] create release PR to pump versions and new section in Changelog #781 
- [x] write announcement

### Use case

plant_layer

**Comment by markus2330** [comment]
After release is before release. For the next participants of the user study, we want to fix the (new) issues of https://github.com/ElektraInitiative/PermaplanT/milestone/4 :seedling: 

The release is scheduled to be on 31.7.2023 so ideally all PRs should be merged the day before, so that we can test+release. :rocket: 

Please help in getting the best release possible. :heart:

**Comment by 4ydan** [comment]
Will do a test report.

**Comment by 4ydan** [comment]
external links(as far as I could judge) and npm audit look good so far, lmk when to rerun them and also the manual test report.

**Comment by markus2330** [comment]
Thank you, I updated the checks above. For manual tests I linked to #743. I think the rest should not be tested before Monday.

**Comment by markus2330** [comment]
New release date is 3.8.2023, so PRs should be ready till 2.8.2023.

**Comment by markus2330** [comment]
Today 17:00 we have a user study participant, so we should be ready asap.

PRs is probably only #771. #737 I don't know yet. Documentation and reformatting is also possible before release.

#684 will be definitely after release, same for #648

https://github.com/ElektraInitiative/PermaplanT/milestone/4 is up to date.

**Comment by markus2330** [comment]
@ThorbenStaufer what do you say? Are happy with dev.permaplant.net, can we release from your point of view?

Basically we only need #743, the rest is optional. But of course we want the best possible experience for participants.

**Comment by markus2330** [comment]
I deploy now 43b51d5af766b804c36a02e1c4e709005d5143e9 on www.permaplant.net

**Comment by markus2330** [comment]
I redeployed to check if also the release deployment works after the simplifications done in #779. It worked, now 8998cf6fb32baec10e8276fa34a5de73ac23ebf0 is deployed, signed and pushed.

So: PermaplanT 0.3.1 released!

Thx to everyone involved in this great job. :heart: 

Please rebase PRs. :rocket:
