### ISSUE TITLE
improve scraper

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#750]
This should be fixed for both

- [ ] the scraper, so that rerunning will lead to correct results
- [ ] fix the current mergedDatasets.csv

### Tasks

 - [ ] delete common_name_de or common_name_en which begin with unique name (the unique name is allowed to be longer)
 - [ ] German name import is a bit broken: remove (Pflanze), (Sorte) und "true" in common_name_de (maybe fix the scraper and rerun)

**Comment by temmey** [comment]
Right now, we use https://www.wikidata.org/ to look up German names. Do we know of better sources where I could fetch German (and maybe scientific) names?
I found https://www.floraweb.de/ and https://www.infoflora.ch/en/, but the plants in their databases seem to be limited to their respective countries, and they include all plants, not just those relevant to permaculture.

**Comment by temmey** [comment]
![image](https://github.com/ElektraInitiative/PermaplanT/assets/20745903/df60ad72-cb49-43b6-92b1-398bdbb30c98)

We have a few cases where we have names with '(.\*)' in them. Some are irrelevant information that I will remove, but for others like 'vogelkirsche (baum)', it's relevant, since there is also a 'vogelkirsche (hecke)' (not in our database). Should I keep it in the '(.\*)' format?

**Comment by markus2330** [comment]
> Right now, we use https://www.wikidata.org/ to look up German names. Do we know of better sources where I could fetch German (and maybe scientific) names?

Wikipedia per se is a very good source, you only need to remove the brackets and make the scraping more robust.

> but for others like 'vogelkirsche (baum)', it's relevant, since there is also a 'vogelkirsche (hecke)' (not in our database). Should I keep it in the '(.*)' format?

Good observation but also this case is irrelevant. So you can discard Baum/Hecke, too. It is no problem if several plants have the same common name, this is why we have unique names :wink:

**Comment by temmey** [comment]
pr #799
