### ISSUE TITLE
map sharing/privacy

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#755]
### Tasks

 - [ ] public: shown by anyone (read-only for non-members, see  #754)
 - [ ] protected: all members
 - [ ] private: only selected persons
