### ISSUE TITLE
improve e2e docu

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#783]
### Tasks

 - [x] ReadMe.md should be renamed to README.md
 - [x] title could be shorter
 - [x] Installation does not describe how to use Dockerfile, probably solves #782
 - [x] Quickstart does not say in which folder I need to be
 - [x] documentation guidelines not used everywhere (e.g. one sentence one line)
 - [x] ENV Variables: is there also .env support?
 - [x] Dont -> Don't or do not
 - [ ] "Make sure to have a solid understanding about the Gherkin syntax" -> link to tutorial

**Comment by 4ydan** [comment]
> is there also .env support?

Good idea. I will commit a .env with default values.

**Comment by 4ydan** [comment]
> "Make sure to have a solid understanding about the Gherkin syntax" -> link to tutorial

Are these links not sufficient? They are at the end of the Writing .feature files section.

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/2733ffdd-30e4-44c5-a67d-c07942da30d8)
