### ISSUE TITLE
Release 0.3.2

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#794]
### Tasks

AFTER #790:

- [ ] manually test dev.permaplant.net according to protocols
- [ ] run external link check (book.toml: follow-web-links)
- [ ] npm audit, fix security problems
- [ ] check/improve reformatting
- [ ] check if all release-critical issues are fixed
- [ ] build <https://build.libelektra.org/job/PermaplanT-Release/>
- [ ] git tag -s vX.X.X
- [ ] git push --tags
- [ ] create release PR to pump versions and new section in Changelog
- [ ] write announcement

### Use case

plants layer introduction tour user study

### Related Pull request

#790

**Comment by markus2330** [comment]
I created #801 which is hopefully the last PR for this release. (Unless a fix for #800 is trivial?)

@temmey From https://github.com/ElektraInitiative/PermaplanT/pull/799 I would like to have an updated mergedDatasets.csv (but it does not necessarily need to be merged before the release)

I already deployed bcb1c1a73abe9659f50a085762c5b7eec233f7e8 on www.permaplant.net

**Comment by temmey** [comment]
i uploaded a new mergedDatasets.csv onto nextcloud - 02412c947e8aa41c3ae92ac264d39b5c10c3fb5f7ca04e52751257eed3bf6a46
