### ISSUE TITLE
use integer for spread and height

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#822]
### Tasks

The user study showed us that people are not happy with these arbitrary 3 classes. Furthermore, we need numbers for the area of plants. So we want:

 - [x] height and spread should be an integer in cm
 - [x] frontend should use spread 1cm = 1px size of icon
 - [x] enums plant_height and plant_spread should be removed
 - [x] minimum sizes for rendering a plant should be 10cm (even if smaller in database)
 - [ ] data quality should be improved, maybe a bit can be fixed with scraper and definitely we can improve using manual overrides  #726

### Use case

plant layer

### Related Pull request

#721

**Comment by markus2330** [comment]
minimum sizes for rendering a plant should be 10cm (even if smaller in database)
