### ISSUE TITLE
Enable all pre-commit hooks in ci

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#832]
### Task

Instead of invoking each hook individually we could just run `pre-commit run -a`.
We need to:

- [ ] fix sqlfluff errors/warnings
- [ ] fix hanging of "Fix Lint groovy findings" (maybe use https://github.com/nice-move/prettier-plugin-groovy instead?)
-  [ ] install packages for the hook `fix-npm-groovy-lint`
-  [ ] remove `cargo-fmt` stage to not perform this check twice
-  [ ] remove npm linting step inside `frontend test` stage to not perform this check twice
-  [ ] install packages for `eslint` `prettier` and `fmt` hook

This would make the pipeline a bit more transparent, as the stage `frontend test` does also `npm format:check`, `npm linting` and `npm test`.
And auto include new checks to the pipeline without needing to manually edit the Jenkinsfile.

**Comment by markus2330** [comment]
@4ydan I think lots of progress happened here? Can you check in the top post what is already done?

**Comment by 4ydan** [comment]
Updated, sadly the other stuff is not that trivial.
We would need to use a dockerfile that has all the backend and frontend stuff needed for the tasks.

**Comment by markus2330** [comment]
As long as there isn't something that is not checked in the CI pipeline at all (but is checked in pre-commit), I don't worry.

**Comment by 4ydan** [comment]
What do we think about the idea to have a pre-commit file in each subdirectory
One in backend
One in frontend
One in e2e

**Comment by markus2330** [comment]
This sounds like a great idea. So the CI would execute the individual checks in each directory (with different Dockerfiles) but for devs it is basically unchanged?

**Comment by 4ydan** [comment]
Another solution seems to be to use the makefile to create different pre-commit targets.
we could create backend, frontend, etc..

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/7f67af6b-20ba-466b-b857-869a6c04c621)

**Comment by markus2330** [comment]
Keeping Makefiles and pre-commit separate sounds better. pre-commit already provides a CLI interface, so I don't see a big benefit in having the targets available in Makefiles, additionally. Or do I miss something important here?

**Comment by 4ydan** [comment]
I just realized this would only work if the subfolders are git submodules or git repos. So we cant do this, as multiple installations of pre-commits is not possible, they overwrite each other.

**Comment by markus2330** [comment]
Let us rest this issue again a bit. Let us pick up again when something changes in pre-commit.

**Comment by markus2330** [comment]
Currently `sql format` fails again and `Fix Lint groovy findings` hangs. So we should get this fixed in CI, to avoid formatting errors creeping in again.
