### ISSUE TITLE
improve ci.md

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#844]
### Tasks

 - [ ] VITE_BASE_API_URL set /
 - [x] E2E in a list,
 - [x] E2E link/videos
 - [x] link checker
 - [x] sanity
 - [x] spell checker
 - [x] What is already my pre-commit?
 - [x] check again what is done in Jenkinsfile
