### ISSUE TITLE
decision: frontend tests using API mocks

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#860]
Goal: better quality with more coverage and have better error messages on refactoring than with e2e tests

### Tasks

 - [ ] choose best library (decision), e.g. https://mswjs.io/
 - [ ] test hooks, e.g. useDebounceEffect
 - [ ] do some tests of whole pages etc.
 - [ ] do some tests of layers

**Comment by markus2330** [comment]
@tschawax do you maybe have experience in this topic?

**Comment by markus2330** [comment]
Maybe you can write the decision&update the test strategy on that point but someone else writes the actual tests later (maybe in the FLOSS course next term).
