### ISSUE TITLE
E2E seed tests

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#865]
### Tasks

According to doc/usecases/*/entry_list_seeds.md

- [x] Test seed creation
- [x] Test seed editing
- [x] Test seed ~~deletion~~ archiving
- [x] Test seed search
- [x] Test seed undo delete
- [ ] Test error case
   - [ ] Invalid expiration date
   - [ ] Same name

**Comment by markus2330** [comment]
Thank you for creating the issue! :heart:

A rough outline what you want to test could be included in the tasks of such an issue.

**Comment by 4ydan** [comment]
Updated.
The usecase is not mentioning that you can search for seeds, but the search functionality exists on the page, so I m not sure about that one.

**Comment by markus2330** [comment]
> The usecase is not mentioning that you can search for seeds, but the search functionality exists on the page, so I m not sure about that one.

Thx for noticing! For this release we simply comment out the whole search, later we reintroduce it properly, see #876

@badnames please remove the search field in seeds, together with fixing the release critical problems in #868
