### ISSUE TITLE
improve tour text

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#871]
### Tasks

Thank you for the amazing review in the tour!

Please

 - [x] create PR with improvements in wording of the tour frontend/src/config/i18n/de/guidedTour.json
 - [x] update tour to also include labels (new in toolbar) or add some generic text that there is also more in the toolbar so that we don't need to constantly update it
 - [x] improve overall UI of the guided tour
 - [x] improve button styles for both themes
 - [x] make call-to-actions more clear and obvious
 - [x] add missing back buttons to some steps

For wording you can always simply create PRs, it is easier to discuss such things in PRs than via issues/text files etc.

### Complexity

3
