### ISSUE TITLE
seed use case left-overs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#872]
### Tasks

- [x] #876
- [x] offer undo for 5 sec before actually deleting a seed
- [x] sorting should be the same as in the map: the one that expire soonest should be at the top, using harvest year if no expire date (`Best by`) given
- [x] Menge/Qualität (e.g. enough and organic) not translated in Overview
- [x] reload of page+greeting when deleting plant (wanted: simply remove element without reload)
- [x] larger notes fields
- [x] Harvest Year needs two lines (should be on one line)
- [x] hover text for the two actions, "archive seed" and "edit seed"
- [x] example for price `2.99€` should be just `2.99`
- [x] example for yield should be good/hoch (lower-case)
- [x]  The paginated select results on creation are not same as the names on the management page.
- [x]  #878
- [x] UC done

**Comment by badnames** [comment]
Seed ordering has been fixed in #882.

**Comment by markus2330** [comment]
> Seed ordering has been fixed in https://github.com/ElektraInitiative/PermaplanT/pull/882.

Is this fix only in the plants layer or is this also for the seeds overview?

I added two more left-overs in the top post:

> 1) larger notes fields which also supports Markdown, see also #722

For now, can you maybe simply make the field bigger so that the user can write multiple lines of normal text in the notes?

There is also a visual problem which might be easily fixable:

> 2) Harvest Year needs two lines

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/6ec83f1f-5858-4e19-b79f-33cf4717e050)

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/d7b48fb8-51cd-457f-ba36-7df3ee69614a)

**Comment by markus2330** [comment]
@badnames I added two more minor things:

- [ ] example for price `2.99€` should be just `2.99`
- [ ] example for yield should be good/hoch (lower-case)

The little things here can all be fixed in #902, to get the release done tomorrow.

**Comment by 4ydan** [comment]
Might add a placeholder to

**Comment by 4ydan** [comment]
I find it a bit confusing that a seed has a plant name. Shouldnt we maybe call it seed name?

**Comment by 4ydan** [comment]
Also is that correct that the names are flipped from the search and the seed management page
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/7d78d8c4-2130-4f44-951b-15bdb841a693)

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/ea04da83-a463-4432-8eee-69ac1a68ee35)

Abelia triflora (indian abelia)
vs
Indian abelia - (Abelia triflora)

Additionally I realized you can enter empty whitespaces as additional name

**Comment by markus2330** [comment]
> I find it a bit confusing that a seed has a plant name. Shouldnt we maybe call it seed name? It doesnt really feel like creating a seed when it has a plant name.

Good point. Actually, it is currently simply called "Complete Name" and can be both for seeds and plants. Maybe we should also extend unique name, to be allowed for seeds (with additional name added). See also doc/database/hierarchy.md

@badnames what do you think about terminology?

> Also is that correct that the names are flipped from the search and the seed management page

When/where did it got flipped?

> Additionally I realized that you can enter empty whitespaces as additional name

Yes, we need to restrict additional names: it should have at least one letter or number and should not contain confusing chars like `-` or `'`.

I added this to #916

**Comment by 4ydan** [comment]
>When/where did it got flipped?

The select box results on creation are not same as the names on the management page.

**Comment by markus2330** [comment]
The examples are fixed by @4ydan, I ticked them in the top post.

A larger notes fields would be also very nice to have (even without Markdown as first step).

**Comment by badnames** [comment]
>  The paginated select results on creation are not same as the names on the management page.

Fixed in #933

**Comment by badnames** [comment]
> Harvest Year needs two lines (should be on one line)

Fixed in #934

**Comment by badnames** [comment]
> larger notes fields

Fixed in #935

**Comment by badnames** [comment]
> UC done

#1001
