### ISSUE TITLE
seed search

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#876]
### Tasks

In its current form the seed search is unusable, please comment it out for the upcoming release. Later it should be fixed with:

 - [x] use case needs to be updated
 - [x] proper debouncing/pagination (with visual indication), reusable component
 - [x] seed search should also include additional name
 - [x] search should search on parts of the whole plant name as shown in overview
 - [x] same seed search should be both in seeds and maps page

### Use case

seed management

**Comment by badnames** [comment]
>  use case needs to be updated

What needs to be updated still?

**Comment by markus2330** [comment]
For now the seed search should be commented out and in the use case you should write that it is currently not available.

**Comment by badnames** [comment]
@markus2330 Good news.

I just managed to fix a critical performance bug in #897 that should make the seed search work now.

As it turns out, new seed pages were requested in an infinite loop, even if there weren't any pages left in the database.
This then prevented setTimeout callbacks from firing within an acceptable timeframe, which in turn slowed down the debouncing hook so much, that the search became basically unusable.

For reference: here is a before and after flamegraph created using chromes dev-tools:

Before:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/7fe9cca9-2962-4f69-b30c-7facf5edd485)

After:
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/8048d9f6-b4a0-4477-9a91-79a17df4d233)

**Comment by badnames** [comment]
P.S. I also accidentally discovered, that this issue would lead to an out of memory error in chrome, when sitting idle on the seeds page for more than ~30 minutes.

**Comment by markus2330** [comment]
Great findings! But nevertheless, please comment out the search for now, as search only for additional name doesn't improve usability.

**Comment by markus2330** [comment]
I added above:

> same seed search should be both in seeds and maps page

That also means that two different searches are available in the right bottom box of the plant layer. Our plant search should still be with the "search" icon (and not immediately the search box shown). (@tschawax we talked about that last time).

Let us discuss this tomorrow and create new issues afterwards so that everything is crystal clear.

**Comment by markus2330** [comment]
@badnames can you please update which PR is connected here?

**Comment by badnames** [comment]
>  same seed search should be both in seeds and maps page

@markus2330 
I'm currently investigating this subtask. 
Just FYI: this will be a slightly bigger undertaking, because this menu would need to be rebuilt:

![Image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/816447d6-0636-4867-810c-ad4d2d50a6dc)


The main reason is it currently does not receive its data from the seeds endpoint.

**Comment by badnames** [comment]
Use case updated in #932

**Comment by markus2330** [comment]
> Just FYI: this will be a slightly bigger undertaking, because this menu would need to be rebuilt:

When you are on it: The left line could be removed.

> The main reason is it currently does not receive its data from the seeds endpoint.

From which endpoint does it get the data instead? Somehow it seems to know the number of seeds after all?

**Comment by badnames** [comment]
> From which endpoint does it get the data instead? Somehow it seems to know the number of seeds after all?

It has its own plant suggestions endpoint that returns a JSON object with a list of PlantSummaryDtos.
Interestingly, this endpoint already uses seeds to generate the suggestion list so it should not be too hard.

I just wanted to let you know that I might not be able to finish this feature within this week, especially considering I have an exam next tuesday.

**Comment by badnames** [comment]
@markus2330 Just so I understood you correctly: you want me to remove suggestions for seasonal plants as outlined in the usecase 'Suggest Plants' and replace them with a seed search?

If you want we could also keep the old display and add a seperate seed search, although I don't think this would be a smart idea from a usability perspective (due to extra clutter).

Another option would be to just add a search function to the existing display for seasonal plants.

**Comment by markus2330** [comment]
The use case doc/usecases/assigned/suggest_plants.md has nothing to do with what has been implemented in this endpoint.

So yes, as discussed: there shouldn't be a preview of seeds but only a search for seeds (identical to the search in https://pr.permaplant.net/seeds).

And ideally you could create one component that can be used for both the plant search and seeds (which has the magnifying glass that allows to type for the search after clicking on it).

Btw. it is efficient to specify behavior using specifications (like use cases or E2E test specifications) . This is more clear than prosa text we are writing now.

**Comment by badnames** [comment]
Yes that is unfortunately a side effect of the search method we are using called trigram matching [pg_tgrm](https://www.postgresql.org/docs/current/pgtrgm.html). 

From the documentation
> pg_trgm ignores non-word characters (non-alphanumerics) when extracting trigrams from a string. Each word is considered to have two spaces prefixed and one space suffixed when determining the set of trigrams contained in the string. For example, the set of trigrams in the string “cat” is “ c”, “ ca”, “cat”, and “at ”. The set of trigrams in the string “foo|bar” is “ f”, “ fo”, “foo”, “oo ”, “ b”, “ ba”, “bar”, and “ar ”.

**Comment by 4ydan** [comment]
ok I see, learned something new, ty

**Comment by markus2330** [comment]
We seem to have a regression: #997

**Comment by badnames** [comment]
#951 has been merged. This should be it for this issue.

**Comment by markus2330** [comment]
Yes!
