### ISSUE TITLE
E2E setup (windows)

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#898]
Basically a small docu for windows/mingw installations

### Tasks

 - [ ] Mention how to install python3-pip
 - [ ] Mention on which operating system the documentation/scripts work
 - [ ] Add env variables for clean_db.py (DATABASE_URL etc)

### Something else

- [ ] Mention in the top readme that the makefile is only for fast execution of frequent tasks, for more detailed executions to look into the seperate folders readme

**Comment by markus2330** [comment]
Thx for creating the issue, would be great to have that mentioned in the documentation. :heart:
