### ISSUE TITLE
Seed: enforce unique constraint.

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#916]
### Tasks

- [x] Each tuple (user, unique_name, additional_name) should only appear once in the database.
- [x] additional names should have at least one letter or number
- [x] additional name should not contain confusing chars like `-`
- [x] trim additional name

### Use case

Seeds

**Comment by markus2330** [comment]
Thanks for creating the PR! The tuple actually should be (user, unique_name, additional_name). Instead of unique_name you can also use the plant ID.

**Comment by markus2330** [comment]
I now changed top post to contain:

- [ ] Each tuple (user, unique_name, additional_name) should only appear once in the database.
- [ ] Yes, we need to restrict additional names: it should have at least one letter or number and should not contain confusing chars like `-` or `'`.

@badnames is this clear and does it cover everything?

**Comment by badnames** [comment]
@markus2330 Do you want to disallow special chars completely (e.g. also # _ , . etc.) or just - and ' ?

**Comment by markus2330** [comment]
Just `-`. Yvonne also likes to use `'`. within additional names.
