### ISSUE TITLE
Frontend usability guideline

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#918]
### Tasks

 - [x] Describe Usability, UI and UX terminology
 - [x] Write UI guideline
 - [x] Write usability guideline

### Related Pull request

#999

**Comment by markus2330** [comment]
Great to have this issue!

I don't think you need to identify problems in the guidelines document (rather in your thesis). For the guidelines, however, you can add rationale and in the rationale you can write that the rule is because of the user study.

The central points of UI guidelines should be about how the UI should consistently look&feel&behave&....

**Comment by markus2330** [comment]
Can you simplify the Tasks so that we can merge a few simple UI guidelines next week?
