### ISSUE TITLE
Timeline: Test the New Timeline Functionality

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#962]
### Tasks

 - [x] Create test cases to verify that the new timeline functionality works as expected, covering various scenarios and edge cases.
 - [x] e2e: check border situations, like jumping a year/month/etc.
 - [x] write unit test for getMonthShortName in `frontend/src/features/map_planning/utils/date-utils.ts`
 - [x] Test if sliders are correctly synchronized

### Use case

TImeline Single Selection
