### ISSUE TITLE
Timeline:  SQL Query to fetch event data

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#966]
## Tasks ##

 - [x] Create a query to retrieve the daily counts of added and removed plants between a timespan
 - [x] Create a query to retrieve the monthly counts of added and removed plants between a timespan
 - [x] Create a query to retrieve the yearly counts of added and removed plants between a timespan

Question: Should the aggregation be done by the query or in the backend?

## Use Case ##

Timeline Event View

### Use case

Timeline Event View

**Comment by markus2330** [comment]
Thank you for creating the issue! I think it is enough to create issues describing the end point  (like you did with #967) and write implementation notes/what the query should do etc. directly there.

Or what do you think @horenso?

**Comment by markus2330** [comment]
@danielsteinkogler is there something open here?

**Comment by horenso** [comment]
This is done.

**Comment by horenso** [comment]
This is done.

**Comment by horenso** [comment]
This is done.
