### ISSUE TITLE
Timeline: Endpoint for fetching event data

### ISSUE THREAD

**Issue by danielsteinkogler** [ElektraInitiative/PermaplanT#967]
### Tasks

As part of the "Map Timeline Event View" feature, we need to create a backend endpoint that delivers the number of plant additions and removals aggregated on a daily, monthly, and yearly basis. This data will be used to populate the Event View feature on the frontend.

- [ ] Daily: Count of plant additions and removals for each day.

JSON Example (just for better understanding)
```
{
  "years": {
    "2000": {
      "additions": 230,
      "removals": 100 
    },
    "2001": {
      "additions": 123,
      "removals": 23 
    },
    "2002": {
      "additions": 421,
      "removals": 200 
    }
  },
  "months": {
    "2000-01": {...},
    "2000-02": {...},
    "2000-03": {...}
  },
  "dates": {
    "2000-10-12": {...},
    "2000-10-13": {...},
    "2000-10-14": {...}
  }
}
```

- [ ] Monthly: Count of plant additions and removals for each month.
- [ ] Yearly: Count of plant additions and removals for each year

- There should be query parameters so that frontend can define start and end date. 
`startDate` and `endDate` in the format `YYYY-MM-DD`

### Use case

Timeline Event View
