### ISSUE TITLE
add note field to plant details

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#977]
### Tasks

 - [x] backend task issue needs to be created (#1067)
 - [ ]  implementation in frontend
 - [x] support for multi-select

**Comment by markus2330** [comment]
@danielsteinkogler you could already create the backend task issue here.

**Comment by markus2330** [comment]
@danielsteinkogler backend task not yet created?

**Comment by danielsteinkogler** [comment]
@markus2330 

- is this issue only meant for the plant note or also for seed note?
- i guess the note filed should only be displayed if only one plant is selected, right?
- the added and removal dates are immediately stored after date is selected. should the notes also be stored with debounce or should we add a save button to save all changed fields in the toolbar?

**Comment by markus2330** [comment]
>  is this issue only meant for the plant note or also for seed note?

Probably it makes sense to add both notes together, depending on availability of backend. The #476 is the list of all the attributes eventually to be added.

>  i guess the note filed should only be displayed if only one plant is selected, right?

If all selected plants have the same note, it would be amazing, if it could be shown or even changed.

> the added and removal dates are immediately stored after date is selected. should the notes also be stored with debounce or should we add a save button to save all changed fields in the toolbar?

It is a general guideline that we always immediately store with debouncing, see solution strategy in the architecture etc.

**Comment by danielsteinkogler** [comment]
@markus2330 
I think tomorrow we should discuss the question of what should happen if multiple plans are selected in our regular meeting.

**Comment by danielsteinkogler** [comment]
@markus2330 update on this issue:
1. I created a backend issue: https://github.com/ElektraInitiative/PermaplanT/issues/1067.

2. The toolbar of the markdown editor wraps lines by default, so it takes up much space.

![Image](https://github.com/ElektraInitiative/PermaplanT/assets/16039038/58e64a57-eb49-4594-a324-ff15b527d598)

Possible solutions:
- hide toolbar and only show the commands to switch between preview, split and edit mode
- only show most important commands in toolbar
- try to make toolbar scrollable (might be tricky)
- try to show toolbar commands depending on width  (might be tricky)

3. We discussed the idea of displaying an alert modal if multiple plants are selected with different notes to inform the user that notes will be overwritten. However, since we use debounced submission, I'm concerned that it won't be very user-friendly if a modal suddenly appears after they stop typing. What do you think @absurd-turtle @badnames?

**Comment by markus2330** [comment]
> hide toolbar and only show the commands to switch between preview, split and edit mode

let us use:

- bold
- todo list
- left or right symbols (split is useless in the toolbar)
- and also full screen mode and then show all symbols when in full screen mode

> We discussed the idea of displaying an alert modal if multiple plants are selected with different notes to inform the 

Let us forget about this popup. The warning symbol would be enough.
