### ISSUE TITLE
Enable CTRL and SHIFT to add/remove single plants to/from an existing selection

### ISSUE THREAD

**Issue by tschawax** [ElektraInitiative/PermaplanT#979]
### Tasks

- [ ] Clicking on an unselected plant while pressing CTRL or SHIFT, adds that plant to an existing selection
- [ ] Clicking on a plant in an existing selection while pressing CTRL or SHIFT, removes it from the selection

Prerequisites
- [ ] Remove the experimental property _shouldOverdrawWholeArea_ so we can access targetted nodes of the transformer (otherwise we can't specifically unselect, i.e. remove, plants from the current selection)
- [ ] After removing _shouldOverdrawWholeArea_, fix stage-, plant- and transformer-dragging

Technical Notes:
Using _shouldOverdrawWholeArea_ enables the transformer dragging from empty space between its nodes. To achieve this, this Konva property overwrites all its internal content with its own shape and that way makes every current node (plant) of the transformer inaccessible. See also https://konvajs.org/api/Konva.Transformer.html#shouldOverdrawWholeArea

### Use case

Multi-Select
